String getLanguageName(String isoCode) {
  switch (isoCode) {
    case "aa":
      return "Afar";
    case "ab":
      return "Abkhazian";
    case "af":
      return "Afrikaans";
    case "ak":
      return "Akan";
    case "am":
      return "Amharic";
    case "ar":
      return "Arabic";
    case "as":
      return "Assamese";
    case "ay":
      return "Aymara";
    case "az":
      return "Azerbaijani";
    case "ba":
      return "Bashkir";
    case "be":
      return "Belarusian";
    case "bg":
      return "Bulgarian";
    case "bh":
      return "Bihari";
    case "bi":
      return "Bislama";
    case "bm":
      return "Bambara";
    case "bn":
      return "Bengali";
    case "bo":
      return "Tibetan";
    case "br":
      return "Breton";
    case "bs":
      return "Bosnian";
    case "ca":
      return "Catalan";
    case "ce":
      return "Chechen";
    case "ch":
      return "Chamorro";
    case "co":
      return "Corsican";
    case "cr":
      return "Cree";
    case "cs":
      return "Czech";
    case "cu":
      return "Church Slavic";
    case "cv":
      return "Chuvash";
    case "cy":
      return "Welsh";
    case "da":
      return "Danish";
    case "de":
      return "German";
    case "dv":
      return "Divehi";
    case "dz":
      return "Dzongkha";
    case "ee":
      return "Ewe";
    case "el":
      return "Greek";
    case "en":
      return "English";
    case "eo":
      return "Esperanto";
    case "es":
      return "Spanish";
    case "et":
      return "Estonian";
    case "eu":
      return "Basque";
    case "fa":
      return "Persian";
    case "ff":
      return "Fulah";
    case "fi":
      return "Finnish";
    case "fj":
      return "Fijian";
    case "fo":
      return "Faroese";
    case "fr":
      return "French";
    case "fy":
      return "Western Frisian";
    case "ga":
      return "Irish";
    case "gd":
      return "Gaelic (Scots)";
    case "gl":
      return "Galician";
    case "gn":
      return "Guarani";
    case "gu":
      return "Gujarati";
    case "gv":
      return "Manx";
    case "ha":
      return "Hausa";
    case "he":
      return "Hebrew";
    case "hi":
      return "Hindi";
    case "ho":
      return "Hiri Motu";
    case "hr":
      return "Croatian";
    case "ht":
      return "Haitian Creole";
    case "hu":
      return "Hungarian";
    case "hy":
      return "Armenian";
    case "ml":
      return "Malayalam";
    default:
      return "Unknown";
  }
}
